github_link: "https://github.com/aditya-azad"
linkedin_link: "https://linkedin.com/in/aditya-azad"
instagram_link: "https://instagram.com/_aditya_azad_"
twitter_link: "https://twitter.com/_aditya_azad_"

github_ssg_link: "https://github.com/aditya-azad/simple-ssg"
